Repository ddRPB/rpb-uploader, pull requests merged in 2022-10, with the labels that each got.

#5 4 fix problems dicovered during uploader integration tests
  config-overrides.js
  package.json
  public/index.html
  src/App.js
  src/index.js
  src/model/DicomUploadDictionary.js
  src/model/DicomUploadPackage.js
  src/test/util/deidentification/DeIdentificationConfiguration.test.js
  src/uploader/DicomParsingMenu.js
  src/uploader/FileUploadDialogPanel.js
  src/uploader/RedirectDialog.js
  src/uploader/SlotPanel.js
  src/uploader/Uploader.js
  src/util/deidentification/DeIdentificationConfigurationFactory.js
  src/util/deidentification/DeidentificationConfiguration.js
  src/util/deidentification/DicomUidService.js
  src/util/logging/Logger.js
  webpack.config.js
Labels: bug

#10 Create SECURITY.md
  SECURITY.md
Labels: documentation

#11 Create codeql.yml
  .github/workflows/codeql.yml
Labels: documentation

#12 build: a new autoprefixer version (> 10.4.5) causes issues in interac…
  package.json
  yarn.lock
Labels: bug

#24 19 refactor dicomstudyselection component add information
  src/model/DicomFile.js
  src/uploader/DicomStudySelection.js
  src/uploader/TreeSelection.js
  src/util/TreeBuilder.js
Labels: enhancement

#29 18 de identification add specific value to 12000063 dicom tag
  src/constants/dicomValueEnums/YesNoEnum.js
  src/test/util/deidentification/DeIdentificationConfiguration.test.js
  src/test/util/deidentification/DeIdentificationConfigurationFactory.test.js
  src/test/util/deidentification/DeIdentificationConfigurationIntegration/RetainDeviceIdentityOption.test.js
  src/test/util/deidentification/DeIdentificationConfigurationIntegration/RetainPatientCharacteristics.test.js
  src/util/deidentification/DeIdentificationConfigurationFactory.js
  src/util/deidentification/DeidentificationConfiguration.js
Labels: enhancement

#28 25 ignored files slow down the firefox window
  src/uploader/DicomParsingMenu.js
  src/uploader/IgnoredFilesPanel.js
  src/uploader/Uploader.js
Labels: enhancement
